### PR TITLE
Naive Pattern Searching Algorithm[Added a code in DSA folder] (Issue #5)

### PR DESCRIPTION
**Pull request by Nandinisaagar**
Written Naive Pattern Searching Algorithm in C programming Language.

### CODE REVIEW

**Comment by rohansaini886** [comment]
please solve conflict

**Review by rohansaini886 — CHANGES_REQUESTED** [review]
please remove .vscode folder from it

**Comment by Nandinisaagar** [comment]
How to resolve this conflict pls help

**Comment by Nandinisaagar** [comment]
Resolved the issue. Please merge

**Pull request merged**
