### PR TITLE
Dynamic Programming and Back tracking question [Added a code in DSA folder] (Issue #5)

### PR DESCRIPTION
**Pull request by Nandinisaagar**
Written the code for the Longest Increasing Subsequence in C++ Programming Language.

### CODE REVIEW

**Review by rohansaini886 — CHANGES_REQUESTED** [review]
please remove .vscode form it

**Comment by Nandinisaagar** [comment]
Resolved the issue. Please merge

**Comment by Nandinisaagar** [comment]
The PR got excluded from hacktoberfest pls merge and add the label after 1st oct if possible

**Comment by sakshi135** [comment]
I want to work on this. Please assign me this.

**Pull request merged**
